FROM mcr.microsoft.com/devcontainers/universal:2-linux
# Install the xz-utils package

RUN apt-get update 
Run pip install django

Run npm install -g @vue/cli

RUN pip install --no-cache-dir Flask Flask-Cors